### ISSUE TITLE
When there are multiple GOPATH, generate a template error

### ISSUE THREAD

**Issue by silenceper** [lileio/lile#26]
When there are multiple GOPATH, generate a template error。

I found this code:

```
templatePath = os.Getenv("GOPATH") + "/src/github.com/lileio/lile/protoc-gen-lile-server/templates"
```

**Comment by arbarlow** [comment]
Hi @silenceper what do mean by multiple GOPATH? There can only be one environment variable set?

**Comment by arbarlow** [comment]
closing since I don't quite understand and future versions of Go may not even have a GOPATH! Happy to take a PR or re-open
