### ISSUE TITLE
Running tests on windows isn't supported

### ISSUE THREAD

**Issue by MrWinstead** [lileio/lile#37]
# Current Behavior

If one tries to run lile-generated tests on Windows, lile will try to use a UNIX socket. This should use something like a named pipe (less realistic, more resilient) or an in-memory transport (more realistic, more complex).

# Expected Behavior

Given a lile-generated test suite
When running ```go test```
Then tests will execute successfully on Linux
and the tests will execute successfully on Windows

**Comment by arbarlow** [comment]
Closing, as it was implemented in #38 !
