### ISSUE TITLE
vendoring lile

### ISSUE THREAD

**Issue by karux** [lileio/lile#49]
I would like to use dep or vgo to vendor the lile framework.  unfortunately, both currently fail due to transitive package dependencies.   

This is due to a transitive dependency on github.com/apache/thrift/lib/go   and github.com/satori/go.uuid, where the authors broke the contract and did not increment the package version.   dep ensure and vgo get    create broken builds. 

satori.uid, where the later version changes the NewV1() signature to return two variables (uid, error) 
TProtobuff.Flush(ctx) now takes a context parameter

Would be helpful to include a normative Gopkg.toml/Gopkg.lock,  and Go.mod   . 

I had to adjust the GoPkg files like so:

GoPkg.toml
[[override]]
  name = "github.com/apache/thrift"
  branch = "master"

[[override]]
  name = "github.com/satori/go.uuid"
  branch="master"

**Comment by arbarlow** [comment]
This is a real pain, I'm aware of this problem. Whilst this would help if you use dep ensure immediately, it doesn't help in that a `go get` is still broken.

**Comment by arbarlow** [comment]
We now support Go modules
