### ISSUE TITLE
Does not support go_package option with semi-colon in proto

### ISSUE THREAD

**Issue by akshaylb** [lileio/lile#51]
Lileio does not currently handle proto files containing go_package options of the following type as supported by [this issue](https://github.com/golang/protobuf/issues/139)

```
option go_package = "github.com/example/foo;bar";
```

Some examples of such usage can be found in some common [googleapis](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto).

**Comment by arbarlow** [comment]
Hi there, I'm afraid I don't have the time or need for this at the moment and I'm not sure how to use. Please could you elaborate or open a pull request. Thanks
