### ISSUE TITLE
Question about import other protos

### ISSUE THREAD

**Issue by xiaowu2008** [lileio/lile#59]
I want to import other protos like import "common/common.proto"; but it shows:

2019/03/20 18:23:02 No go_package option defined for import common/common.proto
--lile-server_out: protoc-gen-lile-server: Plugin failed with status code 1.

once I do not use lile the protoc works fine.

**Comment by arbarlow** [comment]
Hi @xiaowu2008, sorry this took a long time! But this should be fixed here https://github.com/lileio/lile/commit/1848b3ec5a655ab4920a81dd16a276cc1276fc86
