### ISSUE TITLE
support grpc-gateway

### ISSUE THREAD

**Issue by rezam90** [lileio/lile#61]
Hi, It would be awesome to have grpc-gateway support

**Comment by arbarlow** [comment]
Hey @rezam90, you can totally use the gateway!

If you follow this guide https://github.com/grpc-ecosystem/grpc-gateway and add the relevant proto things you can then just add the gateway running stuff to `run.go` which lile generates. I will write some more documentation soon

**Comment by rezam90** [comment]
yes, thanks, I've done it.

I wish there was a built in method in like for it, as it's the same process everyone does to implement.
