### ISSUE TITLE
GO111MODULE=on go get -u github.com/lileio/lile/... fails

### ISSUE THREAD

**Issue by jason-riddle** [lileio/lile#72]
Problem: Running `GO111MODULE=on go get -u github.com/lileio/lile/...` fails with:

```
go get: github.com/openzipkin/zipkin-go-opentracing@v0.3.4 updating to
	github.com/openzipkin/zipkin-go-opentracing@v0.4.5: parsing go.mod:
	module declares its path as: github.com/openzipkin-contrib/zipkin-go-opentracing
	        but was required as: github.com/openzipkin/zipkin-go-opentracing
```

Solutions:

Short Term Fix: I haven't found one, adding the following to go.mod

```
replace (
	github.com/openzipkin/zipkin-go-opentracing v0.3.4 => github.com/openzipkin-contrib/zipkin-go-opentracing v0.3.4
	github.com/openzipkin/zipkin-go-opentracing v0.4.3 => github.com/openzipkin-contrib/zipkin-go-opentracing v0.4.3
	github.com/openzipkin/zipkin-go-opentracing v0.4.5 => github.com/openzipkin-contrib/zipkin-go-opentracing v0.4.5
)
```

leads to the following new error

```
go: github.com/openzipkin-contrib/zipkin-go-opentracing@v0.4.5 used for two different module paths (github.com/openzipkin-contrib/zipkin-go-opentracing and github.com/openzipkin/zipkin-go-opentracing)
```

Longer Term Fix:

- Change dependency name to `github.com/openzipkin-contrib/zipkin-go-opentracing` and bump version if needed (`GO111MODULE=on go get github.com/openzipkin-contrib/zipkin-go-opentracing@latest`). Happy to submit a PR if this feels like the right approach.

**Comment by RoodrigoRoot** [comment]
Hello json, now it shows the next message:
go: github.com/openzipkin-contrib/zipkin-go-opentracing@v0.4.5 used for two different module paths (github.com/openzipkin-contrib/zipkin-go-opentracing and github.com/openzipkin/zipkin-go-opentracing)

:(
